### ISSUE TITLE
Im trying to add Swiftmailer 6.2 to this project

### ISSUE THREAD

**Issue by sarelvdm** [fidanzaEPSI/slim3-flex#3]
Hi,

Im trying to add Swiftmailer 6.2 to this project. Not sure what to do.. Tried to use the email files from the skim3starter. Not getting it right,, can you please provide guidance.

Thanks

**Comment by fidanf** [comment]
Hello,
Good news is: I already know how to implement it. If I have some free time this weekend I shall be able to update the code accordingly. 
Thanks for your patience :)

**Comment by sarelvdm** [comment]
Hello, 
Thank you so much, for the energy / time on this project, May we communicate, via email, Sometime its something very small, I done projects that utilize Slim / Twig, im not an expert, but know my way around it.
Thanks
Sarel

**Comment by fidanf** [comment]
Greetings,
The email feature should work now : [see commit](https://github.com/fidanf/slim3-flex/commit/eccf10f6dea89d2a18e651aeb2a0d92f1c58bf64)

**Comment by sarelvdm** [comment]
Thank you so much
