### ISSUE TITLE
DatabaseServiceProvider and database query builder

### ISSUE THREAD

**Issue by sarelvdm** [fidanzaEPSI/slim3-flex#4]
Hi,

How can I alter the DatabaseServiceProvider to allow the following database selection string to work, Please help.

DB::table('Products')
                ->select(['prodmenuid'])
                ->get();

Thanks

**Comment by caglarkarakoc** [comment]
Hi, 

add the following code to your file.

`use Illuminate\Database\Capsule\Manager as DB;`

**Comment by sarelvdm** [comment]
Thanks

Will try
